//User Costumer
export const MODIFY_NAME_COSTUMER = 'MODIFY_NAME_COSTUMER';
export const MODIFY_EMAIL_COSTUMER = 'MODIFY_EMAIL_COSTUMER';
export const MODIFY_PASSWORD_COSTUMER = 'MODIFY_PASSWORD_COSTUMER';