//User Costumer
export const MODIFY_NAME_COSTUMER = 'MODIFY_NAME_COSTUMER';
export const MODIFY_EMAIL_COSTUMER = 'MODIFY_EMAIL_COSTUMER';
export const MODIFY_PASSWORD_COSTUMER = 'MODIFY_PASSWORD_COSTUMER';

//User Professional
export const MODIFY_NAME_PROFESSIONAL = 'MODIFY_NAME_PROFESSIONAL';
export const MODIFY_EMAIL_PROFESSIONAL = 'MODIFY_EMAIL_PROFESSIONAL';
export const MODIFY_PASSWORD_PROFESSIONAL = 'MODIFY_PASSWORD_PROFESSIONAL';